### ISSUE TITLE
Use Node testrunner for unit tests

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#109]
We may be able to remove some dependencies by using the native Node testrunner for unit tests instead of Vitest.  Requires investigation once the service has been updated from Node 16 to Node 20, where the [Test API](https://nodejs.org/api/test.html) is stable.

**Comment by goosewobbler** [comment]
@christian-bromann Is there also a possibility for WDIO itself to use the Node test runner instead of e.g. Mocha?

**Comment by christian-bromann** [comment]
> Is there also a possibility for WDIO itself to use the Node test runner instead of e.g. Mocha?

We have created an issue a while ago but it hasn't been picked up by anyone.

> by using the native Node testrunner for unit tests instead of Vitest

The problem why I personally haven't use the Node testrunner is its inability to mock modules which is essential for my testing habits. This could be possible by now, not sure. It was definitely something the Node.js team wanted to look into.

**Comment by goosewobbler** [comment]
I didn't realise there isn't module mocking, this seems to be the case still...

**Comment by goosewobbler** [comment]
Closing for now.
