### ISSUE TITLE
Use native WDIO Chromedriver download mechanism

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-electron-service#140]
With the [recent release](https://github.com/webdriverio/webdriverio/releases/tag/v8.14.0) of WebdriverIO that includes new features around [browser driver management](https://webdriver.io/blog/2023/07/31/driver-management) it seems to have broken this service capabilities to do that for the user. I propose to have it set `hostname` and `port` capabilities so that WebdriverIO recognises to not have to setup the browser and driver itself.

Maybe this service can leverage these features and remove some code that prior downloaded Chromedriver.

**Comment by goosewobbler** [comment]
I'll take a look at this when I have a chance

**Comment by goosewobbler** [comment]
@christian-bromann I got the service working again through removal of a lot of code, though the current approach does not set `host` or `port`.

**Comment by christian-bromann** [comment]
Awesome news! Can you raise a PR and I can take a look?

**Comment by goosewobbler** [comment]
#168 (currently WIP)

**Comment by goosewobbler** [comment]
Closing for now as we are going with the first approach [here](https://github.com/webdriverio-community/wdio-electron-service/pull/168#issuecomment-1694527913) which keeps the existing CD download mechanism and passes the binary path to WDIO.  If we find a way to map the electronVersion to the CD version then we can revisit and delegate the download to WDIO.

**Comment by goosewobbler** [comment]
Reopening as we can potentially leverage [electron-to-chromium](https://github.com/kilian/electron-to-chromium) for getting a CD version string.

**Comment by goosewobbler** [comment]
Released with v5.0.0
