### ISSUE TITLE
Electron API support

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#16]
The Spectron fork from which this service was derived supported a number of Electron APIs, we should recreate this but with a different approach.

Despite the size and scope of the APIs provided by Electron, the number of functions which may be useful for testers is actually pretty small, so the greedy property looping and filtering of the Spectron fork can be ditched in favour of a whitelist. This has the benefit of avoiding the problem experienced by the Enzyme React testing library in which users would rely on directly manipulating component state, props, context in their suites, which results in immensely brittle tests; we only really want to be exposing Electron APIs which provide a way of testing values which are difficult or impossible to get hold of through [WebdriverIO Testing Library](https://github.com/testing-library/webdriverio-testing-library) or the `browser` object.

Other constraints on what we allow access to (and how) will be:

- the desire to avoid duplication of WDIO/Webdriver functionality
- the desire to avoid encouraging poor testing practices (c.f. Enzyme) through
  - testing of Electron APIs themselves
  - testing of OS functionality
  - manipulating Electron internals in a way that a user would not have access to via the app  
- the IPC security model; we can't pass complex objects between `main` and `renderer` processes.

API functions can be made available on the `browser` object, namespaced under `electron`. A minimal set of functionality will be exposed to begin with, users can raise issues / submit PRs to expose more Electron functionality if they want and documentation should be updated to encourage this.

This issue will be closed once the initial basic level of API support has been enabled.

**Comment by goosewobbler** [comment]
### API functions / functionality for consideration (* denotes possible priority)

#### [App](https://www.electronjs.org/docs/latest/api/app)
isReady / whenReady - Spectron uses `browser.waitUntil` and `webContents.isLoading` to provide functionality of `waitUntilWindowLoaded` helper.
isDefaultProtocolClient
hasSingleInstanceLock
getAppMetrics
getBadgeCount
getApplicationMenu => Menu.items

#### [BrowserView](https://www.electronjs.org/docs/latest/api/browser-view)
getBounds *
webContents => ?

#### [BrowserWindow](https://www.electronjs.org/docs/latest/api/browser-window)
getBounds *
getAllWindows / getFocussedWindow / getParentWindow / getChildWindows - multi-window support needs some thought.
menuBarVisible
title
getPosition
getTrafficLightPosition
minimizable / maximizable / fullScreenable / closable / movable
isFocused / isDestroyed / isVisible / isModal / isEnabled / isFocusable
isMaximized / isMinimized / isFullScreen / isNormal / isResizable / isAlwaysOnTop / isMenuBarAutohide / isMenuBarVisible
getContentBounds / getNormalBounds / getSize / getContentSize / getMinimumSize / getMazimumSize / getOpacity
capturePage - original Spectron made a big deal out of this...
getBrowserView / getBrowserViews => ?

#### [Clipboard](https://www.electronjs.org/docs/latest/api/clipboard)
various read functions
has / availableFormats
clear

#### [GlobalShortcut](https://www.electronjs.org/docs/latest/api/global-shortcut)
isRegistered

#### [InAppPurchase](https://www.electronjs.org/docs/latest/api/in-app-purchase)
getProducts
canMakePayments

#### [Menu](https://www.electronjs.org/docs/latest/api/menu)
items

#### [NativeTheme](https://www.electronjs.org/docs/latest/api/native-theme)
themeSource *

#### [Process](https://www.electronjs.org/docs/latest/api/process)
getCreationTime / getCPUUsage / getIOCounters
getHeapStatistics / getBlinkMemoryInfo / getProcessMemoryInfo / getSystemMemoryInfo / takeHeapSnapshot

#### [Session](https://www.electronjs.org/docs/latest/api/session)
cookies
clearCache / clearStorageData
setDownloadPath

**Comment by goosewobbler** [comment]
### Use cases for electron APIs
#### `appIsReady` - app startup complete indicating tests can begin
await browser.electron.appIsReady();

#### `waitUntilWindowLoaded` - multi-window apps likely to need this as well as `appIsReady`
await browser.electron.waitUntilWindowLoaded();

#### Testing window positioning (& size, though this is already available to WDIO)
browser.electron.browserWindow.invoke('setPosition');  // called on currently focussed window
browser.electron.browserWindow.invoke('getBounds');  // called on currently focussed window

#### Testing browserView positioning & size - can't see a way of testing this with WDIO
browser.electron.browserWindow.invoke('getBrowserViews');  // called on currently focussed window
browser.electron.browserView.invoke('getBounds', browserViewIndex); // called on currently focussed window

#### Testing app interaction with OS level theme settings
browser.electron.nativeTheme.invoke('themeSource', 'dark');

**Comment by christian-bromann** [comment]
@goosewobbler I think this should be done through Electrons [IPC interface](https://www.electronjs.org/docs/latest/tutorial/automated-testing#using-a-custom-test-driver). We can expose this directly to the tester as well as wrap an API around it. What do you think?

**Comment by goosewobbler** [comment]
Yes, I didn't do anything with this ticket yet - trying to work out potential use cases without exposing the whole thing was kind of fruitless which is a sign I was looking at it the wrong way round, at least in the first instance.  Implementing something like suggested in #18 sounds like a good idea, presumably there is a way to access the electron app process from within the WDIO service launcher?

As a sidenote, when this is done we might want to get that Electron page updated to mention the service.

**Comment by goosewobbler** [comment]
Realised I can just port some more bits of the Spectron fork for this.  Will kick off a PR.

**Comment by goosewobbler** [comment]
PR started in #19

**Comment by goosewobbler** [comment]
Initial APIs delivered
