### ISSUE TITLE
Sending messages through ipcMain?

### ISSUE THREAD

**Issue by jdpaterson** [webdriverio-community/wdio-electron-service#18]
Hi, 

we have an Electron app that is mostly tested through wdio but some tests did rely on Spectron. I was thinking of just writing ipcMain listeners in the test bundle of our app whenever the test suite needs to do some electron-main specific functionality. Does this service provide a way to send a message to ipcMain of the app from our test suite? Or, is there a way to do that even without using this service? 

Thanks

**Comment by christian-bromann** [comment]
Hey @jdpaterson , let's collaborate on this in #16

**Comment by goosewobbler** [comment]
@jdpaterson Electron API hooks have been released in v3.0.
