### ISSUE TITLE
Move service options into capabilities

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#192]
Discussion [here](https://github.com/webdriverio-community/wdio-electron-service/pull/168#issuecomment-1698170654).

**Comment by christian-bromann** [comment]
This is already implemented in https://github.com/webdriverio-community/wdio-electron-service/pull/168 and the updated docs here: https://github.com/webdriverio-community/wdio-electron-service/tree/driver-service-fix#configuration

**Comment by goosewobbler** [comment]
Ah ok, I think I misunderstood, I'll update the E2Es to use this pattern
