### ISSUE TITLE
Electron version not read from package.json if WDIO config is in a subdir

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-electron-service#203]
If the `wdio.conf.js` file is in a sub directory, the service won't find the Electron version automatically anymore because the config file is not located next to a `package.json` anymore. I suggest to use [`pkg-up`](https://github.com/sindresorhus/pkg-up) to find the closest one.

**Comment by goosewobbler** [comment]
Presumably we also want to use `pkg-up` to find the productName for passing to `getBinaryPath` too...

**Comment by christian-bromann** [comment]
Is there any way we can assume a good default here and allow users to set only if desired. It would be amazing if users don't have to set anything if they follow the default setup.

I will look into this.
