### ISSUE TITLE
Improve CLI integration

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#207]
Ideally the WDIO CLI should auto-detect configuration in as many cases as possible when using `electron-builder` or Electron Forge.  Most users should not have to find the path to their app binary themselves.

* Use `pkg-up` to find the nearest package.json
* Analyse the file to determine whether `electron-builder` or `@electron-forge/cli` is being used
	* If no build tool found, ask the user if their Electron app is located in a different repo
	  * If YES, ask for the path to that repo
	    * Analyse the repo's package.json to determine whether `electron-builder` or `@electron-forge/cli` is being used
          * If no build tool found, ask the user for the path to the binary of their app and set `appBinaryPath`
          * If a build tool is found, analyse build tool config
	  * if NO, ask the user for the path to the binary of their app and set `appBinaryPath`
	* If a build tool is found, analyse build tool config

### Build Tool Config Analysis
https://www.electron.build/configuration/configuration
https://www.electronforge.io/config/configuration

* If `electron-builder` is found, try to read config from the following in order:
  * package.json 
  * electron-builder.json (if parse fail - try parsing as JSON5)
  * electron-builder.json5
  * electron-builder.yml
  * electron-builder.toml
* If `@electron-forge/cli` is found, try to read config from the following in order:
  * package.json
  * JS file specified by `config.forge` key in package.json
  * forge.config.js
* Use values read from config (app name, output directory) and `getBinaryPath` to set the `appBinaryPath`
* If configuration for either tool is not found, notify the user, ask the user for the path to the binary of their app and set `appBinaryPath`

**Comment by christian-bromann** [comment]
I raised and released https://github.com/webdriverio/webdriverio/pull/11406 which improves the CLI integration based on the automatic binary detection that landed recently.
