### ISSUE TITLE
PNMP for install

### ISSUE THREAD

**Issue by pmerwin** [webdriverio-community/wdio-electron-service#23]
When running:

npm i -D wdio-electron-service

I am getting:
'''
 npx only-allow pnpm

npx: installed 20 in 3.69s
╔═════════════════════════════════════════════════════════════╗
║                                                             ║
║   Use "pnpm install" for installation in this project.      ║
║                                                             ║
║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
║   For more details, go to https://pnpm.js.org/

```

I am using:
npm: '8.5.2',
  node: '14.18.1'
  
 Is pnmp required to use the service?

**Comment by christian-bromann** [comment]
@goosewobbler can we remove the dependency to pnpm, not many people use it and would get confused.

**Comment by goosewobbler** [comment]
I would have thought this would work but I use PNPM everywhere because it's simply better, so maybe it fell through the cracks.  Obviously it should just work with any package manager...

**Comment by goosewobbler** [comment]
Ok tested and it doesn't work, will try get to this later tonight

**Comment by christian-bromann** [comment]
I can confirm that it works now, thanks for fixing.

**Comment by pmerwin** [comment]
Thanks my dudes!!! 👍
