### ISSUE TITLE
Multi remote for electron apps

### ISSUE THREAD

**Issue by pmerwin** [webdriverio-community/wdio-electron-service#24]
Could we consider extending multi-remote capabilities to this service?

Use cases are to drive more than one app in parallel as well as a browser, etc.

**Comment by christian-bromann** [comment]
Thanks for reporting!

That makes totally sense to me!

Any contributions that resolves the request are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by goosewobbler** [comment]
I think this should be the next thing to go in, need to finish off the API PR but there shouldn't be too much collision if someone wants to start looking at this.

**Comment by goosewobbler** [comment]
Just a few more unit tests to go on #19 and I'll move my attention to this; it will tie in with an investigative piece around E2Es I'm doing as part of my new role but the work is not high priority so will likely still be some weeks.

**Comment by goosewobbler** [comment]
Started a PR - just took code from `wdio-chromedriver-service` and `wdio-geckodriver-service`.

https://github.com/webdriverio-community/wdio-electron-service/pull/26

**Comment by goosewobbler** [comment]
Merged
