### ISSUE TITLE
Improve mocking behavior

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-electron-service#252]
Currently you can mock specific ElectronJS apis via, e.g.:

```ts
await browser.electron.mock('dialog', 'showOpenDialog', 'dialog opened!');
```

This approach has several limitations:

- it doesn't allow to validate whether this method was actually called in the Electron process
- it doesn't allow to execute alternative code

I suggest to align the mocking interface to what we strive for in WebdriverIO as well. The following primitives should be not to difficult to implement in the serviceL

1. an `execute` command that allows to run arbitrary code in the main process

```ts
const res = await browser.electron.execute((electron) => {
  electron.dialog.showOpenDialog('foobar')
  return 123
})
// console.log(res) // outputs 123
```

2. extending the mock command to return a mock object we can use in the mock matchers

```ts
const dialog = await browser.electron.mock('dialog', 'showOpenDialog')
expect(dialog).toBeCalledTimes(2)
expect(dialog).toBeCalledWith('Hello World!')
```

**Comment by goosewobbler** [comment]
Similar has been considered from the API perspective in #107; The proposed solution will also remove need for the `preload` and `main` scripts since the IPC bridge will be no longer required.

**Comment by christian-bromann** [comment]
I think we can just stringify the function and run it in the main process similar to how WebdriverIO uses `execute` to run JS in the browser. I will look into this on my way to NYC.

**Comment by goosewobbler** [comment]
I see, as in https://github.com/webdriverio/webdriverio/blob/main/packages/devtools/src/commands/executeScript.ts#L16?

I did attempt something along these lines when I was prototyping the service initially, but couldn't find a way to get access to the main process.
