### ISSUE TITLE
Make getBinaryPath helper useful when no builder config is found

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#29]
The `getBinaryPath` helper is currently tied to apps built with `electron-builder`.

It might do something different in the case where `electron-builder` (or Electron Forge) is not found, so that you can do for example (MacOS):

```
appBinaryPath: getBinaryPath('/Applications', 'myApp')
```

This would be functionally the same as

```
appBinaryPath: '/Applications/myApp.app/Contents/MacOS/myApp'
```

https://github.com/webdriverio/webdriverio/discussions/8199#discussioncomment-2668229

**Comment by goosewobbler** [comment]
`appPath` / `appName` have been removed, anything more to do in this area needs defining as an enhancement to the `getBinaryPath` helper.

**Comment by christian-bromann** [comment]
@goosewobbler I'ld suggest to have users not need this utility at all and have the service figure out what bundler is used. Some initial development on this is done in #222
