### ISSUE TITLE
Multiremote `execute` calls are returning an array of values for e.g. `app.getName()`

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#313]
See https://github.com/webdriverio-community/wdio-electron-service/blob/cb/better-mock/example/multiremote/api.spec.ts

**Comment by christian-bromann** [comment]
Wouldn't this be an expected behavior? While it is true that you could automate the same Electron app using multi remote you could also set it up so you automate two Electron apps in a single test, e.g. do something in application A and check if it had an effect in application B.

**Comment by goosewobbler** [comment]
My issue here is that the single instance test is still returning two values, shouldn't it return just the value for that instance?

https://github.com/webdriverio-community/wdio-electron-service/blob/cb/better-mock/example/multiremote/api.spec.ts#L22
