### ISSUE TITLE
Flaky interaction E2Es

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#326]
The interaction E2E fails occasionally both locally and (more often) on CI, `BrowserWindow.getFocusedWindow()` sometimes returns null.  Testing with `BrowserWindow.getAllWindows()[0]` shows the same issue, this may be a race condition where the window hasn't been initialised in time for the test.

Example:
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/7160243383/job/19494402693

**Comment by goosewobbler** [comment]
Seems to be failing consistently on CI now.  Still occasional on local runs.

**Comment by goosewobbler** [comment]
Worked around by adding some retries using `specFileRetries` in WDIO config.

**Comment by christian-bromann** [comment]
@goosewobbler we could use the `before` hook to wait until the window is opened, wdyt?

**Comment by goosewobbler** [comment]
Sounds good, I'll take a look at that approach.

**Comment by goosewobbler** [comment]
Prototyped in #340, doesn't work - there's got to be something I'm missing....
