### ISSUE TITLE
Question: Using electron service with WDIO in a script

### ISSUE THREAD

**Issue by arossetter** [webdriverio-community/wdio-electron-service#36]
Hello! I'm having an issue with trying to get the service up and running when using WDIO in a script running Jest. I've tried a couple of things, and the closest I got was doing the following:

Before test, start chromedriver:
`const args = [
      chromedriverPath,
      '--remote-debugging-port=9515',
      '--url-base=/',
      '--verbose',
    ];
    const cdProcess = child_process.spawn(process.execPath, args);`

Then create my remote:
`const app = await remote({
      logLevel: 'trace',
      services: [
        [
          'electron',
          {
            appPath: appPath,
            appName: appName,
            chromedriver: {
              port: 9515,
              chromedriverCustomPath: chromedriverPath,
              logFileName: 'wdio-chromedriver.log',
            },
          },
        ],
      ],
      capabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
          binary: appExecutable,
        },
      },
      port: 9515,
    });`

This will successfully start my electron application and let me do native WDIO things (`app.saveScreenshot()` works as expected), however I get the following error when trying to use `electronApp`:

`TypeError: app.electronApp is not a function
    > 90 |     const appName = await app.electronApp('getName');
         |                               ^
      91 |     console.log(appName);`

I'm admittedly VERY new to WDIO so I'm fully aware that I may be missing something silly, but any advice I could get would be very much appreciated.

Thanks!

**Comment by christian-bromann** [comment]
@arossetter thanks for filing the issue.

Unfortunately this service only works when using the wdio testrunner. I suggest to do that because your tests will look exactly the same as Jest test, given that WebdriverIO uses the same assertion library under the hood.

Let me know if you have further questions.
