### ISSUE TITLE
chrome-driver.bat not installed on windows

### ISSUE THREAD

**Issue by Hraun** [webdriverio-community/wdio-electron-service#37]
The batch file seems to be absent from the package and is not installed on windows, leading to chromedriver startup failure.

**Comment by christian-bromann** [comment]
Hey @Hraun 👋  thanks for filing the issue!

Which batch file are you referring to?

I can see all files correctly being delivered, e.g.

```
❯ l node_modules/wdio-vscode-service/dist/chromium/                                          │
total 69856                                                                                  │
drwxr-xr-x   7 christianbromann  wheel   224B Jun 21 18:35 .                                 │
drwxr-xr-x  30 christianbromann  wheel   960B Jun 21 18:35 ..                                │
-rw-r--r--   1 christianbromann  wheel    66B Jun 21 18:35 index.d.ts                        │
-rw-r--r--   1 christianbromann  wheel   116B Jun 21 18:35 index.d.ts.map                    │
-rw-r--r--   1 christianbromann  wheel    33M Jun 21 18:35 index.exe                         │
-rwxr-xr-x   1 christianbromann  wheel   2.2K Jun 21 18:35 index.js                          │
-rw-r--r--   1 christianbromann  wheel   3.7K Jun 21 18:35 index.js.map
```

**Comment by Hraun** [comment]
Hi. The issue concerns wdio-electron-service. The file I'm referring to is `chrome-driver.bat`, which is supposed to be in the package's `bin` directory. The code now refers to it [here](https://github.com/webdriverio-community/wdio-electron-service/blob/8edc28b45cf00e59515360a050032bcc42d994ba/src/launcher.ts#L47), regardless of the value of `chromedriverCustomPath`. However, in my case, there is no directory ` node_modules/wdio_electron_service/bin` at all, and no file `chromedriver.bat` in `node_modules/bin`. Perhaps it has to do with some specific configuration of my system?

**Comment by christian-bromann** [comment]
I see, indeed, I was able to reproduce it:

```
 npm i wdio-electron-service

added 317 packages, and audited 318 packages in 16s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ l node_modules/wdio-electron-service/
total 48
drwxr-xr-x    8 christianbromann  wheel   256B Jun 22 19:56 .
drwxr-xr-x  257 christianbromann  wheel   8.0K Jun 22 19:56 ..
-rw-r--r--    1 christianbromann  wheel   1.1K Jun 22 19:56 LICENSE
-rw-r--r--    1 christianbromann  wheel   6.4K Jun 22 19:56 README.md
drwxr-xr-x   22 christianbromann  wheel   704B Jun 22 19:56 dist
-rw-r--r--    1 christianbromann  wheel    24B Jun 22 19:56 main.js
-rw-r--r--    1 christianbromann  wheel   2.9K Jun 22 19:56 package.json
-rw-r--r--    1 christianbromann  wheel    27B Jun 22 19:56 preload.js
```

We need to extend the [`files`](https://github.com/webdriverio-community/wdio-electron-service/blob/main/package.json#L89-L93) list to include this directory.

@goosewobbler is this bat expected to be published?

**Comment by goosewobbler** [comment]
@christian-bromann I tried releasing a fix for this but I'm getting this error in the release script:
`WARNING Unable to verify if user wdio-user is a collaborator for wdio-electron-service.`

**Comment by goosewobbler** [comment]
I was not able to release some stuff a couple of months ago but haven't had time to look at it.  Here's a working run:

https://github.com/webdriverio-community/wdio-electron-service/runs/6311500577?check_suite_focus=true

And here's one that doesn't work:

https://github.com/webdriverio-community/wdio-electron-service/runs/7011528217?check_suite_focus=true

**Comment by goosewobbler** [comment]
Hmmm could be https://github.com/release-it/release-it/issues/908

**Comment by goosewobbler** [comment]
Run with debug information:

https://github.com/webdriverio-community/wdio-electron-service/runs/7012013192?check_suite_focus=true

Returning 403 whilst trying to access https://registry.npmjs.org/-/package/wdio-electron-service/collaborators?format=cli

**Comment by goosewobbler** [comment]
Maybe it's a release-it issue then...

**Comment by goosewobbler** [comment]
Release problem fixed.

@Hraun I've released v3.3.0 which has the missing directory - this fixes an issue I was experiencing with `wdio-electron-service-example`, namely that the windows tests were broken.  At some point I want to move the example repo into here and run it as E2Es...

**Comment by christian-bromann** [comment]
Thanks for the fix! Can we close this issue then?

**Comment by goosewobbler** [comment]
I think so, the example repo windows tests all pass now.

**Comment by Hraun** [comment]
@goosewobbler @christian-bromann Thank you, works like a charm.
