### ISSUE TITLE
Conditionally control exposing wdio-electron context bridge items outside test environment

### ISSUE THREAD

**Issue by troppoli** [webdriverio-community/wdio-electron-service#38]
I'm shopping for a Spectron replacement and since I'm looking under the hood...

[Spectron exposed electron app innards by](https://github.com/electron-userland/spectron#node-integration) being constructed in the test runner and either your app has node integration enabled or it conditionally provided a require function for Spectron to use to gain access. So outside of the testing it had no effect (unless the environment var for testing is set during the pre-load). 

The recommended way of [getting at the innards with wdio-electron-service](https://webdriver.io/docs/wdio-electron-service/#api-configuration) it so modify the preload and the content scripts to import scripts that patch the app to expose the innards over the context bridge. This has a lasting effect outside of the testing environment. 

Since we use webpack, conditionally including the scripts doesn't work (we're not setup for dynamic imports yet)... but wrapping the included scripts internally with an if might be a way to accomplish this. Though I might just be missing something!

**Comment by goosewobbler** [comment]
I would say dynamic imports are the way to go here.  What would the conditional check?

**Comment by troppoli** [comment]
I guess the point is that the current suggested integration has a lasting effect outside of the testing environment. It think it's worth pointing out to folks what the risks are for having those apis exposed outside of the testing environment. 

It might be better to suggest that folks use conditional imports for that reason, or if they can't that the take the content of that file an conditionalize it until they can.

**Comment by goosewobbler** [comment]
Definitely agree that the least we should be doing here is updating the documentation to make it obvious that conditional imports should be used.

Not sure about the environment variable route, this effectively means the user is delegating responsibility of exposure to the service at the cost of more integration friction.

**Comment by troppoli** [comment]
I see that in my app's index script, that process.env.WDIO_WORKER is defined.

**Comment by goosewobbler** [comment]
https://github.com/webdriverio-community/wdio-electron-service/pull/42

**Comment by goosewobbler** [comment]
Merged and released
