### ISSUE TITLE
CI: test release blocks a real release by using the same version string

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#390]
Releasing a test version with the tag `next` uses the same version string as a release with the tag `latest`, which means that you can't release a test version, test it and then release that as an official version without incrementing the version.

e.g.
1. `6.1.0` was released with the `next` tag
2. `6.1.0` could not be released with the `latest` tag, because it was already released as `next`.  Received NPM error "You cannot publish over the previously published versions: 6.1.0."
3. `6.1.1` had to be released with the `latest` tag which contained the same code as `6.1.0`, in order to provide an official release for that version.

A release with a different tag from 'latest' should append the tag to the version string, e.g. `6.1.0-next.0`, `6.1.0-beta.2`.  If a release with the same version string exists, the last digit should be incremented.  This should result in the ability to have multiple unique versions utilising the same tag and also enable the following workflow:

1. Release `6.x.y-next.0`, test it manually - fail
2. Release `6.x.y-next.1`, test it manually - fail
3. Release `6.x.y-next.2`, test it manually - pass
4. Release `6.x.y` (same code as `6.x.y-next.2`)

**Comment by seanpoulter** [comment]
I'm going to go out on a limb and guess it's this line:

https://github.com/webdriverio-community/wdio-electron-service/blob/d0afaeb713d83cf0146f1ca41ce0f97c076eba89/.github/workflows/release.yml#L52

For `npm`, we'd need the `--` before the args:

```diff
-  run: pnpm run release:ci --npm.tag=${{github.event.inputs.distTag}} -- ${{github.event.inputs.releaseType}} 
+  run: pnpm run release:ci --  --npm.tag=${{github.event.inputs.distTag}} ${{github.event.inputs.releaseType}} 
```

Let me know if you want a PR.

**Comment by goosewobbler** [comment]
@seanpoulter It would be nice if the fix is as simple as that, I'm happy to test it!

**Comment by goosewobbler** [comment]
@seanpoulter That didn't fix it - output [here](https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8033987815/job/21945020410).  It didn't release anything, I'll revert as the solution is more complex.  I'll update the description as it's not as detailed as it could be.

**Comment by seanpoulter** [comment]
Sorry @goosewobbler.

To build on that, I double checked the [`pnpm` docs](https://pnpm.io/cli/run#options) and the the `--` is not required:

> Any arguments after the command's name are added to the executed script. So if watch runs webpack --watch, then this command:
>```
>pnpm run watch --no-color
>```
>
>will run:
>
>```
>webpack --watch --no-color
>```

--

To go back to the root cause, I believe we published `6.1.0` as a regular release with the `next` tag, not as a pre-release. Reading the [`release-it` docs](https://github.com/release-it/release-it/blob/main/docs/pre-releases.md#manage-pre-releases) for a pre-release it looks like we want either `--preRelease=next` or `--preRelease` which will:

* Add the `"next"` npm tag is set 
* Create a pre-release on GitHub

We can test this using the `--dry-run` flag:

```
$ pnpm run release:ci --preRelease=next --dry-run
```

--

That leads to the question of how do we fix this in code? The solution is pretty simple in webdriverio/webdriverio. They've left a comment saying add `--canary` which for us would be `--preRelease` like this:

```
      distTag:
        description: 'NPM tag (e.g. use "next --canary" to release a test version, add "--force-publish" to release all packages)'
```

Which leads to just:

```diff
        distTag:
-         description: 'NPM tag (e.g. use "next" to release a test version)'
+        description: 'NPM tag (e.g. use "next --preRelease" to release a test version'
```

That means we should be able to test this right now with that `--dry-run` flag. :)

**Comment by seanpoulter** [comment]
Let's try the [Manual NPM Publish](https://github.com/webdriverio-community/wdio-electron-service/actions/workflows/release.yml) with:
```
next --preRelease --dry-run
```

(Christian recently invited me to the org but I'm timid to trigger a release.)

**Comment by goosewobbler** [comment]
@seanpoulter Thanks for diving into this.  I tested `next --preRelease` and also `next --preRelease=next` with the `--dry-run` switch, they both seem to work, resulting in `6.3.3-0` and `6.3.3-next.0`, respectively.

https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8057272785/job/22008037235
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8057187507/job/22007774002

We should be able to get the workflow in the ticket by using a conditional to add `--preRelease=${{ github.event.inputs.distTag }}` to the command when the distTag is not `latest`.  Seems it's not as simple as a ternary though:

https://github.com/actions/runner/issues/409
https://7tonshark.com/posts/github-actions-ternary-operator/

I am assuming that the last version number will increment with subsequent releases of the same tag, we can test this once the above works.

**Comment by christian-bromann** [comment]
Let's make sure to document the release process as part of this effort.

**Comment by seanpoulter** [comment]
Thanks @goosewobbler. You're right, the last digit is incremented by the underlying tool, `release-it`. That'd be quick with an `if` like:

```yaml
  - name: Pre-release
    if: inputs.distTag != "latest"
    ...
  - name: Release
    if: inputs.distTag == "latest"
    ...    
```

--

For the docs, are we good with the input description or should we add a section at the bottom of **docs/development.md** like?

* Development
    * ...
* Release
    * Pre-release -- Run the workflow with `"latest"`. Creates an npm verison, GitHub version, etc.
    * Release -- Run with `"next"`. The suffix is auto-incremented. It Link to the release-it docs. etc.

--

TIL GitHub doesn't support [conditional insertion](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditional-insertion) like Azure DevOps:

```yaml
${{ if inputs.distTag == "latest" }}
  run: pnpm ... --npm.tag=latest
${{ else }}
  run: ..
```

**Comment by goosewobbler** [comment]
> For the docs, are we good with the input description or should we add a section at the bottom of **docs/development.md** like?
> 
>     * Development
>       
>       * ...
> 
>     * Release
>       
>       * Pre-release -- Run the workflow with `"latest"`. Creates an npm verison, GitHub version, etc.
>       * Release -- Run with `"next"`. The suffix is auto-incremented. It Link to the release-it docs. etc.
 
As Christian says I think the whole release process should be documented, we'll want to explicitly link to release-it, the [workflow itself](https://github.com/webdriverio-community/wdio-electron-service/actions/workflows/release.yml) and also mention that the WDIO bot updates the package version as part of the full release.  I think having a section at the bottom of that doc is a good place for it.

> --
> 
> TIL GitHub doesn't support [conditional insertion](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditional-insertion) like Azure DevOps:
> 
> ```yaml
> ${{ if inputs.distTag == "latest" }}
>   run: pnpm ... --npm.tag=latest
> ${{ else }}
>   run: ..
> ```

Yeah, annoying isn't it?  Though more verbose, at least we can use the conditional steps as you detailed above.

**Comment by goosewobbler** [comment]
I'll test the workflow changes merged in #444 as part of releasing 6.4.0, and then close this issue or comment here according to the results.

**Comment by goosewobbler** [comment]
Tested dry runs, they were successful - now releasing a couple of versions of `6.4.0-next.*`.

**Comment by goosewobbler** [comment]
Ok, this still needs some work to get multiple, subsequent pre-releases working - the WDIO bot updated the version of the package to `6.4.0-next.0`, I then created another minor pre-release and we ended up with `6.5.0-next.0`.  I then released a patch dry-run pre-release and got `6.5.1-next.0`.  Ideally we want to be incrementing the last digit when there is an existing pre-release.  I think having a checkbox to apply `--dry-run` would be nice too.

**Comment by seanpoulter** [comment]
Oh, how fascinating. I understand the example in the `release-it` docs now. They don't use a major/minor/patch arg:

>Consecutive beta releases (2.0.0-beta.1 and so on):
>```
>release-it --preRelease
>```

We always provided it so we see the behavior you described. :facepalm: The solution seems to be make that releaseType optional for pre-releases which would support your initial use case, but also let you publish a pre-release for a future version:

> Given I am at v6.3.2
> When I publish a major pre-release with the tag "alpha"
> Then I expect v7.0.0-alpha.0 to be published

Any preference on the final result?

**Comment by seanpoulter** [comment]
Have a look at #460. That might do it. :thinking:

**Comment by goosewobbler** [comment]
@seanpoulter That looks great - I think ultimately this sort of logic should be extracted into an action but there are certainly higher priorities for the service development - I'm happy to merge #460 and give it a test run.

**Comment by seanpoulter** [comment]
I've made it ready for review. I was debating creating two workflows.

**Comment by goosewobbler** [comment]
I tested subsequent pre-releases, seems to work although getting 422 when creating the github release.  Is this because there are no changes?  The npm version is published and the WDIO bot updates the package version.

https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8211588209/job/22460721293
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8211712054/job/22461024964

**Comment by seanpoulter** [comment]
Interesting.

The `422 Unprocessable Entity` is documented here. https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#invalid-request. It reads like the response body should explain exactly what's wrong. The logs say:

```
✖ GitHub create release
ERROR 422 (Invalid request.

For 'properties/body', nil is not a string. - https://docs.github.com/rest/releases/releases#create-a-release)
```

When I read that I believe the `body` is not set when we try to create the release.



It sounds like it might be expected ooks like we could add the `--ci` flag to skip the release if there are

**Comment by seanpoulter** [comment]
Interesting.

The `422 Unprocessable Entity` is documented here. https://docs.github.com/en/rest/using-the-rest-api/troubleshooting-the-rest-api?apiVersion=2022-11-28#invalid-request. It reads like the response body should explain exactly what's wrong. The logs say:

```
✖ GitHub create release
ERROR 422 (Invalid request.

For 'properties/body', nil is not a string. - https://docs.github.com/rest/releases/releases#create-a-release)
```

When I read that I believe the `body` is not set when we try to create the release.

Based on [the API docs](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release--parameters) the `body` is not a required property. I wonder if we're sending `null` or `nil` and it breaks. :thinking: 

Based on https://github.com/release-it/release-it/issues/1014#issuecomment-1591160357 it seems like we could prevent this using the `--ci` flag.

**Comment by seanpoulter** [comment]
For what it's worth I've documented the issue in https://github.com/release-it/release-it/issues/1014#issuecomment-1986725953 and proposed a fix. :wink:

**Comment by goosewobbler** [comment]
@seanpoulter thanks again for your work, digging through all this.  I think we are applying the `--ci` flag:

https://github.com/webdriverio-community/wdio-electron-service/blob/main/package.json#L59

You can see it in the output [here](https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8211712054/job/22461024964).

**Comment by goosewobbler** [comment]
Technically this ticket is completed with the updates to the release workflow already merged.  I'll raise new tickets for anything outstanding.
