### ISSUE TITLE
Provide utility function to allow using this service without the testrunner

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-electron-service#412]
This is inspired by a conversation in https://github.com/webdriverio/webdriverio/issues/12128

It would be nice to provide a way to allow users to use this service in a normal Node.js script without having to use the testrunner. I could see a custom `remote` method taking the same parameters as the `webdriverio` version would do but internally would run all the hooks before returning the instance. Note that `beforeCommand` or `afterCommand` work in standalone too.

**Comment by goosewobbler** [comment]
@christian-bromann this sounds somewhat related to #331, perhaps it's the same solution.

**Comment by christian-bromann** [comment]
@goosewobbler these features are different. #331 is about allowing users to test an Electron app without bundling it. This issue describes a feature where a user can use this service without having to run the wdio testrunner. Imagine a Node.js script like this:

```ts
import { startSession } from 'wdio-electron-service`

const ide = await startSession({
  electronVersion: '1.2.3',
  appBinaryPath: './path/to/bundled/electron/app.exe',
  appArgs: ['foo', 'bar=baz'],
})
```

where `startSession` takes a parameter to define the Electron application (no `WebdriverIO.Config` - instead only properties related for Electron automation) and returns a `WebdriverIO.Browser`.

**Comment by goosewobbler** [comment]
Got it, I thought they were separate but was being overly optimistic there is a chance one might solve the other...

**Comment by christian-bromann** [comment]
Thanks for the work @goosewobbler - I released the docs: https://webdriver.io/docs/desktop-testing/electron/standalone
