### ISSUE TITLE
Expense workflow failures

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#449]
Looks like we missed something with this workflow:

https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8116095466
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8115379138

**Comment by christian-bromann** [comment]
Seems like the `expense.yml` was committed as folder:

<img width="174" alt="Screenshot 2024-03-01 at 11 26 33 AM" src="https://github.com/webdriverio-community/wdio-electron-service/assets/731337/73103475-e314-4ed5-ac4a-c8417967bc26">

**Comment by seanpoulter** [comment]
Ahahaha. :facepalm:
