### ISSUE TITLE
wdio-electron-service & docker: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by joonne** [webdriverio-community/wdio-electron-service#46]
Hey, trying to run cucumber tests against electron inside docker in Jenkins and we're seeing this kinda error:

```
Request failed with status 500 due to unknown error: Chrome failed to start: exited abnormally.
(DevToolsActivePort file doesn't exist)
(The process started from chrome location ... is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

Internet suggests that I should be passing `--disable-dev-shm-usage` flag for the chromium, but haven't been able to do that.
Any helpers or advice that I might have overlooked?

I'm doing a migration from spectron to wdio at the moment.
The docker entrypoint making use of xvfb was configured already for spectron and I guess it should work similarly for the wdio also?

wdio.conf.ts
```
  services: [
    [
      'electron',
      {
        appPath: join(__dirname, '../../../package'),
        appName: productName,
        appArgs: [
          "--disable-infobars", // not sure if this is needed
          "--disable-dev-shm-usage",
          "--no-sandbox", // not sure if this is needed
          "--headless",  // not sure if this is needed
        ],
        chromedriver: {
          port: 9519,
          logFileName: 'wdio-chromedriver.log',
        },
      },
    ],
  ],

```

Grateful for any tips :)

**Comment by goosewobbler** [comment]
Hi @joonne,

This is a very common and irritating error, one which I struggled with for quite a few days over the initial development of `wdio-electron-service` (back then it was still a Spectron fork).  I couldn't get the tests to work on github actions across platforms and what solved it for me in the end was a combination of flags, some of which you mention, and using the xvfb github action on linux.

I left the flags in the service so you shouldn't need to pass them in appArgs:

https://github.com/webdriverio-community/wdio-electron-service/blob/main/src/service.ts#L121

Could be that the isCI check is failing, if you check the wdio logs (need to be set to a minimum level of 'debug') you should be able see the exact browsercapabilities set for a given run which includes the args passed to chromium.  You might also want to put some additional debug into your local copy of the service.  I don't claim that the flags currently specified will fix all instances of this error so if you manage to find a chromium flag or another change to the service that fixes it we can see about getting that into the code.

**Comment by joonne** [comment]
Hey, thanks for the reply!

I'm currently trying to debug if the flags from `isCI` are passed down to the app, and also trying to run locally the service but struggling a bit with the npm linking etc. I'll try to come up with something that works for our use case and then submit PR or some other input of the results. It was already super relieving that I was kinda on the right track and all of this trial & error is needed as it is an unknown issue. Thanks :open_hands:

**Comment by goosewobbler** [comment]
No problem, good luck.  I knew it wouldn't be long before someone would be experiencing this issue with the service.

**Comment by christian-bromann** [comment]
I think it would be nice if we document solutions to this problem, maybe in the `README.md` so that people know what to do without having to search for years.

**Comment by goosewobbler** [comment]
@christian-bromann yes, I'll use this issue as a tracker for that as any documentation may also be affected by the OP's findings.

**Comment by joonne** [comment]
I found out the issue for our problem, it was in fact a missing dependency in our docker image. This was revealed by trying to run chromium (or our own electron app) inside the container. The missing library in our case was [libgbm1](https://packages.debian.org/sid/libgbm1), and after this was installed, the DevToolsActivePort issue was gone.

Not sure if it is relevant to be documented in this package's documentation, but it seems there are multiple ways to end up in this particular error :man_shrugging: Maybe some notion about running in docker would be in place also?

**Comment by goosewobbler** [comment]
@joonne glad you fixed it, presumably the library was needed for xvfb to work properly. This particular error is a difficult one but if enough people have the same error and report them here as issues we can keep updating the docs for common solutions.
