### ISSUE TITLE
CI: release workflow dry run issues

### ISSUE THREAD

**Issue by goosewobbler** [webdriverio-community/wdio-electron-service#474]
The WDIO release bot updates the version in `package.json` whenever the release workflow is run.  Ideally dry run releases should be exempt from this.  Additionally, the tag is created in NPM which definitely shouldn't be happening.

Dry run of releasing `6.4.0`:
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8247240217/job/22554950063

After this run, the WDIO bot updated the `package.json`, which was then reverted:
https://github.com/webdriverio-community/wdio-electron-service/commits/main/package.json

Actual release - fails due to `6.4.0` tag already existing:
https://github.com/webdriverio-community/wdio-electron-service/actions/runs/8247330093/job/22555225164

**Comment by goosewobbler** [comment]
Pinging @seanpoulter and @christian-bromann in case they have any insight - it seems the `6.4.0` release effectively went ahead with the dry run, and the subsequent "real" release did nothing.

**Comment by seanpoulter** [comment]
Yea, it's my fault. This is a good signal to get better sleep. I guess I forgot to push the code that **uses** `dryRun`.

**Comment by goosewobbler** [comment]
No worries, and no apologies needed!  Thanks for the quick fix.

**Comment by goosewobbler** [comment]
Closing, should be fixed by #475
