### ISSUE TITLE
Chromedriver process on Windows not cleaned up after specs complete

### ISSUE THREAD

**Issue by sparerd** [webdriverio-community/wdio-electron-service#50]
# Overview
While testing out the [wdio-electron-service-example](https://github.com/goosewobbler/wdio-electron-service-example) project on a Windows machine I noticed that the chromedriver process was not being cleaned up after running the test suite (with `npx wdio`).

# Details
I believe [this line in the launcher](https://github.com/webdriverio-community/wdio-electron-service/blob/b4fda1dda675edd8f775bd3eba47f7bb9c392573/src/launcher.ts#L55) is the start of the issue (snippet copied below).
```ts
if (isWin) {
  process.env.WDIO_ELECTRON_NODE_PATH = process.execPath;
  process.env.WDIO_ELECTRON_CHROMEDRIVER_PATH = chromedriverServiceOptions.chromedriverCustomPath;
  chromedriverServiceOptions.chromedriverCustomPath = join(__dirname, '..', 'bin', 'chrome-driver.bat');
}
```

This is overriding any path to chromedriver (whether custom or default) to instead use [this .bat file](https://github.com/webdriverio-community/wdio-electron-service/blob/b4fda1dda675edd8f775bd3eba47f7bb9c392573/bin/chrome-driver.bat).
```bat
@echo off
"%WDIO_ELECTRON_NODE_PATH%" "%WDIO_ELECTRON_CHROMEDRIVER_PATH%" %*
if ERRORLEVEL 1 exit /b 1
exit /b 0
```

Now, this does make sense since the default `chromedriverCustomPath` points to `node_modules\electron-chromedriver\chromedriver.js`. However, the .bat file does not wait for node to exit before the terminal running the .bat file is allowed to exit. Node is allowed to keep running while its original parent terminal process has died, which causes problems in the `wdio-chromedriver-service`.

[At this line](https://github.com/webdriverio-community/wdio-chromedriver-service/blob/975c81add005aafe23e60a4cc00a2edb1dfc836e/src/launcher.ts#L100) of the `wdio-chromedriver-service` the child process for chromedriver is spawned and a reference kept, although because of the .bat file override earlier, `this.process` refers to the terminal process that will soon start Node.

By the time we hit the `this.process.kill()` command in the `onComplete` service handler, `this.process` has already long since died and the Node/chromedriver processes are running as their own process tree, disconnected from `this.process`.

An example process tree might look like this (pids taken from my last run):
```
cmd.exe (28956) [this.process] <-- dies immediately after node.exe is started
|____ node.exe (22832)
      |____ chromedriver.exe (24100)
```

# Solution
A real solution to this issue will likely involve tracking the child node process or communicating with it to collaboratively shutdown. Unfortunately I don't have anything like that to offer right now, though I do have a relatively small workaround fix that would at least mitigate the problem.

The use of the .bat file launcher seems to only make sense if a chromedriver file is provided that needs to run within node (js file). If a user provides a path to chromedriver.exe in `chromedriverCustomPath`, it is currently still passed through to the .bat file to be run in Node. I propose that we only use the .bat file for .js files and allow any other extension to be run directly via `child_process.spawn()`.

Something like ([in launcher.ts](https://github.com/webdriverio-community/wdio-electron-service/blob/b4fda1dda675edd8f775bd3eba47f7bb9c392573/src/launcher.ts)):
```ts
import { join, extname } from 'path';
// snip...

if (isWin) {
  process.env.WDIO_ELECTRON_NODE_PATH = process.execPath;
  process.env.WDIO_ELECTRON_CHROMEDRIVER_PATH = chromedriverServiceOptions.chromedriverCustomPath;
  const shouldRunInNode = extname(chromedriverServiceOptions.chromedriverCustomPath) === '.js';
  if (shouldRunInNode) {
    chromedriverServiceOptions.chromedriverCustomPath = join(__dirname, '..', 'bin', 'chrome-driver.bat');
  }
}
```

This would allow anyone encountering this issue to specify the chromedriver.exe path themselves and bypass the extra .bat file redirection (from wdio.conf.js):
```js
const config = [
services: [
    [
      'electron',
      {
        appPath: join(__dirname, 'dist'),
        appName: productName,
        appArgs: ['foo', 'bar=baz'],
        chromedriver: {
          port: 9519,
          logFileName: 'wdio-chromedriver.log',
          // provide custom path to .exe to bypass use of .bat file
          chromedriverCustomPath: require.resolve('electron-chromedriver/bin/chromedriver.exe'),
        },
      },
    ],
  ],
  // snip...
]
```

This work around solves the problem in my case. Specs in the example project complete successfully and the chromedriver process dies at the end. If the work around is acceptable, I would be happy to submit a PR.

**Comment by goosewobbler** [comment]
Hi @sparerd, thanks for the detailed issue description.  I'm definitely interested in improving the service usage in Windows, however there are bigger fish to fry at the moment - I'm currently working on a major update addressing these three thorny issues: #35 #31 #27.

When these are working I'll look at the Windows situation before the release.

**Comment by christian-bromann** [comment]
@sparerd feel free to provide a PR with a fix if interested.

**Comment by goosewobbler** [comment]
This was also reported in [`wdio-electron-service-example`](https://github.com/goosewobbler/wdio-electron-service-example/issues/21).

**Comment by m4hdyar** [comment]
I'm using this as a workaround :
```
onComplete: async function (exitCode, config, capabilities, results) {
    shell.exec('taskkill /IM chromedriver.exe /F', { silent: true });
    shell.exec('kill -9 $(pgrep chromedriver)', { silent: true });
}
```

**Comment by goosewobbler** [comment]
Workaround released with v4
