### ISSUE TITLE
Possibility of using devtool protocol instead of chromedriver ?

### ISSUE THREAD

**Issue by pillsilly** [webdriverio-community/wdio-electron-service#51]
Just curious

**Comment by christian-bromann** [comment]
Can you provide more context why you would like to use the devtools protocol? Technically I don't see a reason why this should not work.

**Comment by pillsilly** [comment]
> Can you provide more context why you would like to use the devtools protocol? Technically I don't see a reason why this should not work.

Though wdio has done some work to hide driver protocol differences in API level, but not all of them could be done perfectly - in fact there are still many of them left to the user handle with
I know that's not wdio's fault, it's because of the natural difference between chrome driver and gecko driver and devtools.

Like the behavior of listening to alert, 
Like getText/getHtml could return different result if the element contains some special characters (like /n, &nbsp), 
Like browser log handling,
and so on and so on.

After many practices, it seems the simplest way could be to just use the **same protocol** for your product **when testing it in different platform/browser** -- even if you're using wdio.

Our app is tested in FF, Chrome and Electron
now it's kinda embarrassing that  we have used devtool and Chrome and even Firefox, 
for Electron which is chromium based we have no devtool path available yet.

**Comment by goosewobbler** [comment]
Being honest I don't know what's involved here, or if it requires changes to this service and / or WDIO.

**Comment by christian-bromann** [comment]
@pillsilly thanks for providing more input. I honestly would recommend __not__ to rely on the devtools protocol. It is proprietary and can change between every Chrome version. The WebDriver protocol is better suited as it doesn't change and features are tested. If you need features that are only available in the devtools protocol I would just switch to it if necessary but do all other automation through WebDriver.

Again, given that Chromedriver also just uses the devtools protocol I assume it is possible to attach yourself to it. The service is currently starting the session via WebDriver. I am sure same is possible via DevTools. It would require to start the app with some additional parameter I assume. There could be a service option defining how to start the session. If you are interested implementing this feature, let us know.
