### ISSUE TITLE
Detect universal mac binary (electron-builder)

### ISSUE THREAD

**Issue by seanssel** [webdriverio-community/wdio-electron-service#565]
`electron-builder` supports building for "universal" arch on Mac, placed in `mac-universal`.

https://www.electron.build/api/electron-builder.html#Arch

**Comment by goosewobbler** [comment]
Forge also supports this: https://www.electronforge.io/cli#options-3

I assume you mean that we need to update [this line](https://github.com/webdriverio-community/wdio-electron-service/blob/main/src/application.ts#L37) to account for the "universal" case for Mac / Electron Builder projects.  Unfortunately EB doesn't use systematic paths like Forge does, so it will have to be something like:

```
p.arch === 'x64' ? 'mac': `mac-${p.arch}` 
```

**Comment by goosewobbler** [comment]
@seanssel Do you have an example of the `electron-builder` config you are using for this universal binary?

**Comment by seanssel** [comment]
> @seanssel Do you have an example of the `electron-builder` config you are using for this universal binary?
> 
> EDIT: never mind, using a different approach now.

Hey, pretty simple config - this is all I have in the mac target portion. Also nice to hear I'm not the only one struggling with electron-builder documentation...

`mac: {
      ...
      
      target: {
        target: 'default',
        arch: 'universal',
      },
    }`

**Comment by goosewobbler** [comment]
Yeah, I don't recommend using EB at all in new projects, Forge is much better.  Anyway I have to support both here...

This issue should be closed pretty soon, fix is in the pipeline.

**Comment by seanssel** [comment]
I opened an issue for this on the EB repo in any case. 

Yeah looking back I would have preferred to use Forge, but there's no way we'd consider swapping out such a major part of our build process right now.

Thanks for looking at this so quickly, I appreciate you!

**Comment by goosewobbler** [comment]
Released in `6.6.0`
