### ISSUE TITLE
SyntaxError: Unexpected token 'export' wdio-electron-service/dist/cjs/index.js:35

### ISSUE THREAD

**Issue by maxhellwig** [webdriverio-community/wdio-electron-service#62]
Hello,  
after initiating a new project using `npm init wdio .', and configuring the electron service as described [here](https://webdriver.io/docs/wdio-electron-service), I'm getting the following error message:
```
@wdio/runner: wdio8-test/node_modules/wdio-electron-service/dist/cjs/index.js:35
export {};
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (wdio8-test/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.hookedLoader [as _load] (wdio8-test/node_modules/mockery/mockery.js:111:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
```
The wdio.conf.ts is this:
```ts
import type { Options } from "@wdio/types";
import * as path from "path";

export const config: Options.Testrunner = {
  runner: "local",
  outputDir: "all-logs",
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      files: true,
      project: "./tsconfig.json",
      transpileOnly: true,
    },
  },
  specs: ["./features/**/*.feature"],
  exclude: [],
  maxInstances: 10,
  capabilities: [
    {
      maxInstances: 5,
      browserName: "chrome",
      acceptInsecureCerts: true,
    },
  ],
  logLevel: "trace",
  bail: 0,
  baseUrl: "http://localhost",
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: [
    [
      "electron",
      {
        appPath: path.join(__dirname, "binaries"),
        appName: "App Name",
        electronVersion: "22.0.0",
      },
    ],
  ],
  framework: "cucumber",
  reporters: ["spec"],
  cucumberOpts: {
    require: ["./features/step-definitions/steps.ts"],
    backtrace: true,
    requireModule: [],
    dryRun: false,
    failFast: false,
    snippets: true,
    source: true,
    strict: false,
    tagExpression: "",
    timeout: 60000,
    ignoreUndefinedDefinitions: false,
  },
};
```
and the package.json like this:
```json
{
  "name": "wdio8-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "wdio": "wdio run ./wdio.conf.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@wdio/cli": "^8.6.7",
    "@wdio/cucumber-framework": "^8.6.6",
    "@wdio/local-runner": "^8.6.7",
    "@wdio/spec-reporter": "^8.6.6",
    "chromedriver": "^111.0.0",
    "prettier": "^2.8.6",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.2",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-electron-service": "^4.0.0"
  }
}
```
node version is 18.15.0, tried it also with node 16.14.0.
For me, it looks like it tries to use the CommonJS version of wdio-electron-service, but everything else uses esm already. 

Might this be a problem?

Setting `"type": "module"` in package.json leads to this error instead:

> wdio run ./wdio.conf.ts

2023-03-22T09:14:30.671Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///wdio8-test/wdio.conf.ts: exports is not defined in ES module scope
ReferenceError: exports is not defined in ES module scope
    at file:///wdio8-test/wdio.conf.ts:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Process finished with exit code 1

**Comment by christian-bromann** [comment]
@maxhellwig thanks for raising the issue. Which WebdriverIO version are you using? Note that the latest version of the Electron service requires WebdriverIO v8.

**Comment by maxhellwig** [comment]
Hello @christian-bromann, thank your for the response. WebdriverIO 8 has been used, like stated in the `package.json`.
Today I found a solution for it. I renamed the files to explicitly mark them as `type: module` using the `.mts` extension:
![image](https://user-images.githubusercontent.com/54803377/227135513-8da80ab7-ce09-4b59-a33c-9f6cd6c3b2a9.png)

Now the tests start and work as expected.

This this the wdio.conf.ts:
```ts
import { getDirname } from "cross-dirname";
import { join } from "path";

export const config = {
  runner: "local",
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      files: true,
      esm: true,
      project: "./tsconfig.json",
      transpileOnly: true,
    },
  },
  specs: ["./features/**/*.feature"],
  exclude: [],
  maxInstances: 10,
  capabilities: [{}],
  logLevel: "trace",
  bail: 0,
  baseUrl: "http://localhost",
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: [
    [
      "electron",
      {
        appPath: join(getDirname(), "binaries"),
        appName: "Miele MOVE Device Connector",
        electronVersion: "22.0.0",
      },
    ],
  ],
  framework: "cucumber",
  reporters: ["spec"],
  cucumberOpts: {
    require: ["./features/step-definitions/steps.mts"],
    backtrace: true,
    requireModule: [],
    dryRun: false,
    failFast: false,
    snippets: true,
    source: true,
    strict: false,
    tagExpression: "",
    timeout: 60000,
    ignoreUndefinedDefinitions: false,
  },
};
```
the tsconfig.json
```json
{
  "ts-node": {
    "esm": true,
    "require": ["tsconfig-paths/register"],
    "compilerOptions": {
      "module": "CommonJS"
    }
  },
  "compilerOptions": {
    "noEmit": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "moduleResolution": "Node",
    "target": "ESNext",
    "module": "ES2020",
    "types": [
      "node",
      "@wdio/globals/types",
      "expect-webdriverio",
      "@wdio/cucumber-framework"
    ]
  },
  "files": ["./features/**/*.ts", "./features/**/*.mts"],
}
```
And I added tsconfig-paths as dependency, but currently I'm not sure if this is required:
```json
{
  "name": "wdio8-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "wdio": "wdio run wdio.conf.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@wdio/cli": "^8.6.7",
    "@wdio/cucumber-framework": "^8.6.6",
    "@wdio/local-runner": "^8.6.7",
    "@wdio/spec-reporter": "^8.6.6",
    "chromedriver": "^111.0.0",
    "prettier": "^2.8.6",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.5",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-electron-service": "^4.0.0",
    "tsconfig-paths": "4.1.2",
    "cross-dirname": "^0.1.0"
  }
}
```

When taking your demo app, I could provide an example repository. But for me it seems, like somehow the ESModule/CommonJs separation does not work properly. In the target project, I cannot simply set `"type": "module"` on root level yet.

**Comment by christian-bromann** [comment]
@goosewobbler do you think this service would still work in a CJS project?

**Comment by goosewobbler** [comment]
@christian-bromann the example app used for the E2Es is CJS.  Perhaps the local dependency link is masking an issue though?

**Comment by goosewobbler** [comment]
@maxhellwig @christian-bromann Not sure why the E2Es still work but seems the built CJS version is being built with an extra, undesired line at the bottom.  This isn't in the source so it must be some broken build configuration.

```
export {};
```

https://www.npmjs.com/package/wdio-electron-service/v/4.0.0?activeTab=code

**Comment by goosewobbler** [comment]
Needs a separate tsconfig for CJS: https://github.com/webdriverio-community/wdio-electron-service/pull/64

**Comment by goosewobbler** [comment]
@maxhellwig Try `4.0.2`

**Comment by maxhellwig** [comment]
Hey guys, just checked the new version! I can confirm that the new version works! I have not quiet understood what the changes do, can you explain it a little bit further? Beside from that, this issue is resolved :-)

**Comment by goosewobbler** [comment]
@maxhellwig Basically the repo is set up to build an ESM module with a CJS wrapper which allows a user to `require` the module in a CJS project without errors.  ESM projects will bypass the wrapper and use the underlying module directly.  The problem was that the typescript compilation step of the build was outputting `export {};` at the bottom of the CJS wrapper entry point, which breaks the wrapper as when you have an export statement like this it is assumed that the file is ESM.  

As @christian-bromann mentioned, this has been an issue with other webdriver repos and can simply be fixed by removing the line from the built files before publishing.  However I found a more elegant fix in completely separating the ESM and CJS build processes and ensuring that they use different TSConfig files - having a CJS-specific TSConfig ensures that the problematic line is not added to the built file without breaking the ESM version.
