### ISSUE TITLE
Electron Dialog Support?

### ISSUE THREAD

**Issue by Meceron** [webdriverio-community/wdio-electron-service#67]
Hi!

I really like your work! Now I've just ran into a problem, there is a  button with no inputto file upload in a project. I need to handle the electron dialog with sendkeys or just retrun some value as close event. Is there any solution for that?

Thanks and again great work!

**Comment by goosewobbler** [comment]
@Meceron there isn't a solution for this currently, I'll see if I can put together an API for mocking the electron dialog - it would behave as the second case here and would likely be limited to the async dialog methods.

**Comment by Meceron** [comment]
Hello, that would be great! But could You show me the second case are you speaking about? I just need to send some text to a dialog then close it.

**Comment by goosewobbler** [comment]
The second case is the one you mentioned above - returning some value as a close event.  Mocking the dialog means it wouldn't actually open but you could verify that it was called and specify some return value.

**Comment by Meceron** [comment]
Ah that would be great!

**Comment by goosewobbler** [comment]
@m4hdyar I couldn't find `--require` in the Electron CLI docs, do you have another reference for it?

https://www.electronjs.org/docs/latest/api/command-line-switches

**Comment by m4hdyar** [comment]
@goosewobbler I couldn't also find it in the documentation but this is the code itself
https://github.com/electron/electron/blob/7982c6cee2ffde77ad3122803c0cc646d08cdaab/default_app/main.ts#LL50C2-L52C14
and here is the description
https://github.com/electron/electron/blob/7982c6cee2ffde77ad3122803c0cc646d08cdaab/default_app/main.ts#LL269C1-L286C4

If you also open electron from the commandline you'll see it.
And it does work if you:

1. Override the dialog object in another module. 
2. Then open electron using commandline and preload the script using --require
3. Now do something that opens a dialog and it does work

If it does not work for you too, we can create an issue in https://github.com/electron/electron.

PS: I think if we could find out why it does not work with child_process.spawn, then we can also inject the  
```
if (isTest) {
  import('wdio-electron-service/preload');
}
```
without changing the production code too.

**Comment by goosewobbler** [comment]
@m4hdyar thanks for that, and yes good idea about potentially injecting the service IPC handling - not sure if preload would also work when injected as i suspect `require` is only going to work for main process modules, but worth a try.  I'll see if I can reproduce the issue.

**Comment by Meceron** [comment]
Hello, is there anything up about it?

**Comment by goosewobbler** [comment]
@m4hdyar Did you try using the `appArgs` config item?  I'm investigating setting `--require` there.

**Comment by m4hdyar** [comment]
> @m4hdyar Did you try using the WDIO `execArgv` config item? I investigated setting `--require` there overriding dialog and also for the main process IPC handling. It seems to work in that logs from the file appear - but not with ESM (for obvious reasons). In CJS I can't currently get it to require another node module, e.g. `require('electron')` just returns the path of the Electron executable.
> 
> EDIT: I think this might be a security thing to prevent required scripts getting at electron internals...

No I haven't tried it yet but I'm using ESM. As you said it does not work with ESM. Do you see a workaround for it ?

**Comment by goosewobbler** [comment]
No, I couldn't find a workaround - perhaps when full ESM support lands in Electron there will be an update for this functionality.

**Comment by m4hdyar** [comment]
> No, I couldn't find a workaround - perhaps when full ESM support lands in Electron there will be an update for this functionality.

I guess this PR can help us! 
https://github.com/electron/electron/pull/37535

**Comment by goosewobbler** [comment]
@Meceron I released the mock API and dialog access with v4.1.  You can specify a return value which will be returned when the mocked function is called.  I have some plans to improve this as it doesn't yet allow for specifying a function, but thought I'd release early and iterate.

```ts
await browser.electron.mock('dialog', 'showOpenDialog', 'dialog opened!');
const result = await browser.electron.dialog('showOpenDialog');
console.log(result); // 'dialog opened!'
```

**Comment by Meceron** [comment]
Thank you!

**Comment by Meceron** [comment]
I've ran into a problem:

[electron 22.0.0 win32 #0-0] Cannot read properties of undefined (reading 'electron')
[electron 22.0.0 win32 #0-0] TypeError: Cannot read properties of undefined (reading 'electron')

page.ts
```
  async waitForFileUpload(selector: string, path: string) {
    await browser.electron.mock('dialog', 'showOpenDialog', path)
    const result = await browser.electron.dialog('showOpenDialog')
    console.log('result:' + result)
  }
```

main.ts
```
require('wdio-electron-service/dist/preload')
require('wdio-electron-service/dist/main')
```

what did I do wrong?

**Comment by goosewobbler** [comment]
@Meceron not sure what's going on here but you have both IPC scripts in your main process which is likely to cause some issues.  The preload goes in your preload script.
