### ISSUE TITLE
Document minimal required Electron version needed to use the service without manually configuring Chromedriver

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-electron-service#705]
As a user trying to set up tests on my project that is using Electron v18 I am getting confused when I get the following error message:

> Failed downloading chromedriver v100: Download failed: server returned code 404. URL: 

Can we:

1. document in the readme what the minimum required version needs to be?
2. can we maybe add a check in the code to provide a better error message?

**Comment by goosewobbler** [comment]
We've got this in the Chromedriver configuration:  
https://github.com/webdriverio-community/wdio-electron-service/blob/main/docs/configuration/chromedriver-configuration.md#user-managed

I think we can mention the minimum required Electron version to avoid having to self-configure chromedriver on the main README, and also update the error message.
