### ISSUE TITLE
`browser.switchFrame()` accepts only `await`ed Electron elements

### ISSUE THREAD

**Issue by gavvvr** [webdriverio-community/wdio-electron-service#818]
Based on [`switchFrame()`](https://webdriver.io/docs/api/browser/switchFrame/) WDIO docs,
the following should work:

```javascript
await browser.switchFrame($('iframe'))
```

It's also proven by [e2e test](https://github.com/webdriverio/webdriverio/blob/v9.2.10/e2e/wdio/headless/test.e2e.ts#L517-L526) in main WDIO repository:

```javascript
it('should reset the frame when the page is reloaded', async () => {
    await browser.url('https://the-internet.herokuapp.com/iframe')
    await expect($('#tinymce')).not.toBePresent()
    await browser.switchFrame($('iframe'))
    await expect($('#tinymce')).toBePresent()
    await browser.refresh()
    await expect($('#tinymce')).not.toBePresent()
    await browser.switchFrame($('iframe'))
    await expect($('#tinymce')).toBePresent()
})
```

However `await browser.switchFrame($('iframe'))` construct
won't work with `wdio-electron-service` unless `$('iframe')` is `await`ed.

I reproduced it in https://github.com/gavvvr/wdio-electron-service-818 by having the same iframe displayed as on https://the-internet.herokuapp.com/iframe page and using the [same e2e test](https://github.com/webdriverio/webdriverio/blob/v9.2.10/e2e/wdio/headless/test.e2e.ts#L517-L526) from primary webdriverio repository.

This bug is especially annoying for me, because I have a TypeScript setup with typescript-eslint type-aware linting rules enabled:
<img width="950" alt="image" src="https://github.com/user-attachments/assets/19f6e6bd-9e14-4c12-9730-be08c98d5013">
Also, the best [practices guide webdriver.io guide](https://webdriver.io/docs/bestpractices#lazy-loading-and-promise-chaining) says:
> You should always use await __with the exception of the `$` and `$$` command__.

**Comment by goosewobbler** [comment]
Closing for now, following the WDIO issue and will adjust types in the service if necessary.

**Comment by gavvvr** [comment]
@goosewobbler the issue in primary WDIO repository was fixed. Does it make sense to add e2e test with `iframe` to this repository?

**Comment by goosewobbler** [comment]
Sure.  I added some tests with `$` but I don't have a problem with testing `iframe` specifically.
