### ISSUE TITLE
 Support for multiple configuration file formats(electron-builder)

### ISSUE THREAD

**Issue by mato533** [webdriverio-community/wdio-electron-service#819]
### Description
We are using `electron-builder` with a YAML formatted configuration file.
When I tried to run E2E tests using this wonderful library, I realized that it only supports configuration files in json format.
Referring to the [official documentation](https://www.electron.build/configuration.html),  `electron-builder` supports not only `Json` but also `YAML` and `TOML` format files.

I think it should also support automatic loading using configuration files other than Json.

#### Related code

https://github.com/webdriverio-community/wdio-electron-service/blob/cf6ff613684b311fc2d5ebab40c9fc8150d34b82/packages/%40wdio_electron-utils/src/index.ts#L182-L193

### Workaround
Specify the `appBinaryPath` option in my capabilities.

**Comment by goosewobbler** [comment]
Agreed, this should be a thing.  
YAML support should be pretty easy by using https://www.npmjs.com/package/yaml.
TOML equivalent only supports 0.4.0 of the spec: https://www.npmjs.com/package/toml
However there is [smol-toml](https://www.npmjs.com/package/smol-toml) which looks like a good modern option for parsing TOML.

**Comment by mato533** [comment]
Thank you for considering.
I think there are 2 options resolving this issue.
Do you think that policy #1 is desirable?(Sorry if your comment took #2 into account.)

1. Parses the configuration file independently 
   Implemented using libraries suggested in the comment.

1. Reuse electron-builder's configuration file reading implementation
   Use [`app-builder-lib`](https://github.com/electron-userland/electron-builder/tree/master/packages/app-builder-lib). This library is used internally by `electron-builder` when reading configuration files.
   However, since it is used internally, I think it may be subject to change.
   (In this case, [`findAndReadConfig`](https://github.com/electron-userland/electron-builder/blob/3d8e402f0ff1930de9c009dd78ee6dd8fe9c6133/packages/app-builder-lib/src/util/config/load.ts#L46-L56) may be useful.)

**Comment by mato533** [comment]
By the way, when I implemented Option.2 experimentally, it seems to work, but a mysterious error occurs in the unit test of `wdio-electron-service`.  I don't know the root cause due to my lack of knowledge, but it seems that the mock using `nock` is causing the problem...

**Comment by mato533** [comment]
@goosewobbler 
Thank you for the reply.
I have created PR(#823) using `app-builder-lib` and commented about the issue.
I apologize for my incompetence, but I would appreciate your help in reviewing the code and resolving the issue.

> By the way, when I implemented Option.2 experimentally, it seems to work, but a mysterious error occurs in the unit test of `wdio-electron-service`. I don't know the root cause due to my lack of knowledge, but it seems that the mock using `nock` is causing the problem...
