### ISSUE TITLE
Feature request of the Option for `startElectron`

### ISSUE THREAD

**Issue by mato533** [webdriverio-community/wdio-electron-service#856]
### Description
I'm trying to launch the electron application using `startElectron` to integrate with vitest.
But the function has limited options. we cannot pass the parameter for `goog:chromeOptions`.
The reason of trying to pass the parameter is running test with headless mode that is require some chrome options.

Considering into some PR(#852), it might be a good idea to also allow `rootDir` and `browserVersion` (which actually determine the electron version) to be specified as parameters.

#### Related Code
[here](https://github.com/webdriverio-community/wdio-electron-service/blob/32457f60382cb4970c37c7f0a19f2907aaa32443/packages/wdio-electron-service/src/session.ts#L10)

### Expected behavior
This library can be inputed the parameter for 'goog:chromeOptions' and passdown to capabilities in `startElectron`.
Considering into some Documents, code and PR, we also can be inputed following parameters.

- `goog:chromeOptions` ([related docs](https://webdriver.io/docs/capabilities/#run-browser-headless))
- `wdio:chromedriverOptions` ([related docs](https://github.com/webdriverio-community/wdio-electron-service/blob/main/docs/configuration/chromedriver-configuration.md#user-managed))
-  `browserVersion ` (related PR: #852)
-  `rootDir` ([related code](https://github.com/webdriverio-community/wdio-electron-service/blob/32457f60382cb4970c37c7f0a19f2907aaa32443/packages/wdio-electron-service/src/launcher.ts#L23-L26))

### Workaround
Copy the logic of  `startElectron` (which actually `init` of `session.ts`) and adjust to be able to pass the parameter needed.
Sample code is [here(my repository)](https://github.com/mato533/vitest-plugin-wdio-electron/blob/main/packages/vitest-plugin-wdio-electron/src/electron.ts)

**Comment by hpsjakob** [comment]
I'd also found it usefull to pass the logLevel (https://github.com/hpsjakob/wdio-electron-service/tree/feature/logLevel).

**Comment by mato533** [comment]
@hpsjakob 
Thank you for your comment.
but it(parameter for `remote`) only define the log level of `webdirver`.
the log level of `wdio-electron-service` seems to be [setted using environment variables](https://github.com/webdriverio/webdriverio/blob/05e280ba48a2844844e74d1fe665d682005f91bb/packages/wdio-logger/src/index.ts#L147).

The logging level for `webdriver` can also be set with the same environment variable [(WDIO_LOG_LEVEL)](https://webdriver.io/docs/api/environment/#wdio_log_level), so I think users of this package would be better off setting the environment variable separately rather than as a library option.

**Comment by goosewobbler** [comment]
I think rather than pass all these options in separately, we just allow users to specify the capabilities and testRunnerOpts (which includes `rootDir`).  I'll start a PR for this, there's some additional changes for the types and some interface clarification around the `clearMocks`, `resetMocks` and `restoreMocks` properties I want to get in too.

**Comment by mato533** [comment]
@goosewobbler 
Another concern is regarding `testRunnerOpts`. Being able to specify it is simple and nice. On the other hand, I am worried that the other parameters of `testRunnerOpts` may mislead users into thinking that they can influence the behavior of this library.

Judging from the [actual code](https://github.com/webdriverio-community/wdio-electron-service/blob/32457f60382cb4970c37c7f0a19f2907aaa32443/packages/wdio-electron-service/src/launcher.ts#L23-L26), it seems that only rootDir is included in TestRunnnerOpts.

**Comment by goosewobbler** [comment]
@mato533 I've started looking at this in #858, we can collaborate there.  The standalone feature is one of the newer features of the service, so it hasn't had as much time spent on it as some other parts.

`testRunnerOpts` has been amalgamated into `electronServiceGlobalOptions` which includes `resetMocks`, `restoreMocks` and `clearMocks` - three options which are applied globally and make less sense when applied to individual capabilities.

**Comment by goosewobbler** [comment]
@mato533 @hpsjakob I released this update as a pre-release `wdio-electron-service@next`.  The main differences are, `startElectron` is now `startWdioSession`, and you can pass in the same capabilities that WDIO accepts, so you now need to specify `browserName` but you can also provide e.g. `goog:ChromeOptions`, `wdio:chromedriverOptions`, `browserVersion`.

```
const browser = await startWdioSession([
  {
      'browserName': 'electron',
      'browserVersion': '33.2.1',
      'wdio:electronServiceOptions': {
        appBinaryPath: '/path/to/binary',
      },
      'goog:chromeOptions': {
        args: ['--disable-dev-shm-usage', '--disable-gpu', '--headless'],
      },
      'wdio:chromedriverOptions': {
        binary: '/path/to/chromedriver',
      },
  },
]);

Let me know if you have any further issues or raise an issue and a PR if there's something which doesn't work for you.

**Comment by mato533** [comment]
@goosewobbler 
Thank you for this enhancement ! It seems to be working fine for me.

**Comment by goosewobbler** [comment]
This is technically a breaking change as the interface is now completely different for the standalone mode, so I will release it as v8.
