### ISSUE TITLE
Document Testing Electron Applications in the main docs

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-electron-service#88]
We should add a section to the main documentation "Electron Testing" with some documentation how to get started with this service and what a user needs to do to test an Electron application. It would be also nice if we could maybe integrate this into the WDIO configuration wizard.

**Comment by christian-bromann** [comment]
I started working on this and will include Electron testing within the configuration wizard.

**Comment by christian-bromann** [comment]
Added docs here: https://webdriver.io/docs/desktop-testing/electron

Also setting up Electron tests in now part of the configuration wizard. @goosewobbler wanted to give it a spin? I wasn't quite able to get the example app to work so I wonder if the whole workflow works for you.

**Comment by goosewobbler** [comment]
@christian-bromann Docs look great.  I found some CJS build issues, fixed in 4.2 - this might be the cause of the example not working for you...

**Comment by christian-bromann** [comment]
Awesome, thanks a lot @goosewobbler 🎉
